-- MySQL Script generated by MySQL Workbench
-- Sun May 28 17:35:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema react-node-compo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema react-node-compo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `react-node-compo` DEFAULT CHARACTER SET utf8 ;
USE `react-node-compo` ;

-- -----------------------------------------------------
-- Table `react-node-compo`.`CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `react-node-compo`.`CATEGORIES` (
  `idCat` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomCat` VARCHAR(255) NOT NULL,
  `creat_at_cat` TIMESTAMP(4) NOT NULL,
  PRIMARY KEY (`idCat`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCat_UNIQUE` ON `react-node-compo`.`CATEGORIES` (`idCat` ASC) ;


-- -----------------------------------------------------
-- Table `react-node-compo`.`PRODUITS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `react-node-compo`.`PRODUITS` (
  `idPro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomPro` VARCHAR(45) NULL,
  `descPro` LONGTEXT NOT NULL,
  `prixPro` INT NOT NULL,
  `imagePro` VARCHAR(50) NOT NULL,
  `creat_at_pro` TIMESTAMP(4) NOT NULL,
  `idCat` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPro`),
  CONSTRAINT `fk_PRODUITS_CATEGORIES`
    FOREIGN KEY (`idCat`)
    REFERENCES `react-node-compo`.`CATEGORIES` (`idCat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPro_UNIQUE` ON `react-node-compo`.`PRODUITS` (`idPro` ASC) ;

CREATE INDEX `fk_PRODUITS_CATEGORIES_idx` ON `react-node-compo`.`PRODUITS` (`idCat` ASC) ;


-- -----------------------------------------------------
-- Table `react-node-compo`.`CLIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `react-node-compo`.`CLIENTS` (
  `idCli` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomCli` VARCHAR(45) NOT NULL,
  `numCli` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCli`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCli_UNIQUE` ON `react-node-compo`.`CLIENTS` (`idCli` ASC) ;


-- -----------------------------------------------------
-- Table `react-node-compo`.`COMMANDES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `react-node-compo`.`COMMANDES` (
  `idCmd` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPro` INT UNSIGNED NOT NULL,
  `idCli` INT UNSIGNED NOT NULL,
  `prixCmd` INT NOT NULL,
  `qteCmd` VARCHAR(45) NOT NULL,
  `create_cmd` TIMESTAMP(4) NOT NULL,
  `livrer` INT NOT NULL,
  PRIMARY KEY (`idCmd`),
  CONSTRAINT `fk_PRODUITS_has_CLIENTS_PRODUITS1`
    FOREIGN KEY (`idPro`)
    REFERENCES `react-node-compo`.`PRODUITS` (`idPro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PRODUITS_has_CLIENTS_CLIENTS1`
    FOREIGN KEY (`idCli`)
    REFERENCES `react-node-compo`.`CLIENTS` (`idCli`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_PRODUITS_has_CLIENTS_CLIENTS1_idx` ON `react-node-compo`.`COMMANDES` (`idCli` ASC) ;

CREATE INDEX `fk_PRODUITS_has_CLIENTS_PRODUITS1_idx` ON `react-node-compo`.`COMMANDES` (`idPro` ASC) ;

CREATE UNIQUE INDEX `idCmd_UNIQUE` ON `react-node-compo`.`COMMANDES` (`idCmd` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
